defmodule Example.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:regions, primary_key: false) do
      add :country_id,
          references(:countries, column: :id, name: "regions_country_id_fkey", type: :uuid)

      add :population, :bigint, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:landmarks, primary_key: false) do
      add :city_id, references(:cities, column: :id, name: "landmarks_city_id_fkey", type: :uuid)
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:countries, primary_key: false) do
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:regions, [:name], name: "regions_name_index")

    create unique_index(:countries, [:name], name: "countries_name_index")

    create table(:cities, primary_key: false) do
      add :region_id,
          references(:regions, column: :id, name: "cities_region_id_fkey", type: :uuid)

      add :population, :bigint, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:landmarks, [:name], name: "landmarks_name_index")

    create unique_index(:cities, [:name], name: "cities_name_index")
  end

  def down do
    drop_if_exists unique_index(:cities, [:name], name: "cities_name_index")

    drop_if_exists unique_index(:landmarks, [:name], name: "landmarks_name_index")

    drop constraint(:cities, "cities_region_id_fkey")

    drop table(:cities)

    drop_if_exists unique_index(:countries, [:name], name: "countries_name_index")

    drop_if_exists unique_index(:regions, [:name], name: "regions_name_index")

    drop table(:countries)

    drop constraint(:landmarks, "landmarks_city_id_fkey")

    drop table(:landmarks)

    drop constraint(:regions, "regions_country_id_fkey")

    drop table(:regions)
  end
end